apiVersion: apps/v1
kind: Deployment
metadata:
  name: rightontime-backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: rightontime-backend
  template:
    metadata:
      labels:
        app: rightontime-backend
    spec:
      containers:
        - name: backend
          image: nicolenarvaez/rightontime-backend:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: rightOnTime.settings
            - name: DJANGO_SECRET_KEY
              value: "django-insecure-z3o=kf0_e4q&z*rkv34e9e)kqg&&*fe@inrr)pdwh=(gy2g7w5"
            - name: DEBUG
              value: "False"

          
