apiVersion: v1
kind: Service
metadata:
  name: rightontime-backend-service
spec:
  selector:
    app: rightontime-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
